version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TheBestPassworInThisWord!123
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Source/Web/Dockerfile
    depends_on:
      - db
